"""import turtle
wn=turtle.Screen()
wn.bgcolor("green")
ays=turtle.Turtle()
ays.color("white")
ays.pensize(3)
ays.left(90)
ays.forward(150)
ays.left(90)
ays.forward(50)
ays.right(180)
ays.forward(100)

wn.exitonclick()"""
import turtle
wn=turtle.Screen()
wn.bgcolor("pink")
ays=turtle.Turtle()
ays.color("blue")
ays.pensize(3)
ays.right(90)
ays.forward(150)
ays.left(90)
ays.forward(50)
emr=turtle.Turtle()
emr.pensize(3)
emr.color("orange")
emr.left(180)
emr.forward(50)

wn.exitonclick()